### ISSUE TITLE
[Bug]:  Aqara FP1 Zone Setting - Apply button missing...

### ISSUE THREAD

**Issue by pauloon** [nurikk/z2m-frontend#1759]
### What happened?

In my Aqara FP1 Exposes screen, in the region settings, I cannot set it because the "Apply" button does not show up.

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/48531854/0d708cc6-c9f3-4c6c-b490-b6da790187c9)

In this screen (from Google), you can see that there is an Apply button there:
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/48531854/f007161a-001d-4002-81fe-081bc3a9965e)

How can we fix that?

Thanks,
Paulo.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by pauloon** [comment]
@nurikk .... @Koenkk ... Can you please, help?
Thanks!

**Comment by pauloon** [comment]
up

**Comment by pauloon** [comment]
up

**Comment by pauloon** [comment]
up?

**Comment by cherryocola** [comment]
up

**Comment by Koenkk** [comment]
> @nurikk .... @Koenkk ... Can you please, help? Thanks!

I will take a look at this ASAP, it also causes this issue: https://github.com/Koenkk/zigbee2mqtt/issues/19240#issuecomment-1763467981

**Comment by pauloon** [comment]
> > @nurikk .... @Koenkk ... Can you please, help? Thanks!
> 
> I will take a look at this ASAP, it also causes this issue: [Koenkk/zigbee2mqtt#19240 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/19240#issuecomment-1763467981)

Thanks!
Please, let me know when it is solved.

**Comment by makeitworktech** [comment]
Having this issue as well! I get an error as soon as I click the Region Upsert input field:
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/90069122/5eec5dd5-fcf4-4e17-a016-2a1cb8f932a8)

**Comment by Koenkk** [comment]
Should be fixed now (https://github.com/nurikk/zigbee2mqtt-frontend/commit/3df395b774816b7605cf34699c4e9cdf288f1b56), please confirm

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by carsaig** [comment]
Not fixed yet. Issue persists - even in current dev branch. Chrome Browser, Firefox & Safari affected on Mac.

**Comment by papatistos** [comment]
This isn what the UI looks for me:

![CleanShot 2024-02-18 at 14 22 57@2x](https://github.com/nurikk/zigbee2mqtt-frontend/assets/3662750/1ff264a8-0a81-4085-aed5-ade08501ae2b)

So it looks like there is one apply button for the entire region, which seems to be correct. But pressing it seems to have no effect no (no feedback in UI and the region doesn't seem to register). 

Is there supposed to be any kind of confirmation in the UI? Or an error message when somnething goes wrong?

**Comment by greyman12** [comment]
I am seeing the same issue. I have also tried to set the region manually but this seems to also fail.

**Comment by xX-Nexus-Xx** [comment]
I was able to define the regions manually earlier .. but somehow it does not work anymore :( 

1) I'm deleting and creating 10 regions with this flow (was working before)
`[
    {
        "id": "0e2a9fc870fe4f89",
        "type": "group",
        "z": "a991523747fb3b93",
        "name": "",
        "style": {
            "fill": "#c8e7a7",
            "label": true,
            "color": "#000000"
        },
        "nodes": [
            "3b19efbd19473515",
            "3872aa19e748932a",
            "fbd2b6edef523743",
            "5aa6837c84af53c0",
            "2fddda6527966677",
            "ba62f19b42a5081c",
            "ed38aba3837eb7af",
            "ec9c608fb99ee855",
            "a7d208e06324c3f8",
            "4b8e0477421a11e0",
            "47a64bdd7d804fb3",
            "92d0ca57f11f6740",
            "9b2e67a8ab9f6a7b",
            "646055b5fb834ab4",
            "c40fd0fd8f11ade6",
            "cebb925c35150179",
            "1d9ed62194557284",
            "adb49031091b093c",
            "bbafb2d7588f44d1",
            "b5de0006461c431f",
            "2e85f9e108c90cd7",
            "c8e054f576e56f58",
            "f410949de42697c2",
            "a8b618ed1f826f0c",
            "8b2f2349794948e7",
            "42aa0c5214e677c2",
            "1f66b62b1797928e",
            "76b63ddea61ce5b1",
            "cb9db60b16f57df8",
            "8668ef70969923c4",
            "776cb0f58d4a0167",
            "9dcb35836c217104",
            "dcd25ce11a4c1be2",
            "f42bbaba3918a204",
            "00b0c574ab7519c0",
            "591e048d831b202f",
            "56f80df860cf83ff",
            "1d0c9872d7b5272f",
            "f48124d8afbf74c0",
            "48e1ba0527324388",
            "79562e1fbc7b00d2",
            "b80a4c2b66078508",
            "f254c4b7b9b06a3c",
            "20ee7e58f47f6130",
            "b35d1b8240e37478"
        ],
        "x": 874,
        "y": 879,
        "w": 1002,
        "h": 462
    },
    {
        "id": "3b19efbd19473515",
        "type": "inject",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "Init",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 990,
        "y": 920,
        "wires": [
            [
                "3872aa19e748932a"
            ]
        ]
    },
    {
        "id": "3872aa19e748932a",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "topic",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "zigbee2mqtt/Living.Motion/set",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1130,
        "y": 920,
        "wires": [
            [
                "fbd2b6edef523743"
            ]
        ]
    },
    {
        "id": "fbd2b6edef523743",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 1",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":1}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 920,
        "wires": [
            [
                "5aa6837c84af53c0",
                "1f66b62b1797928e"
            ]
        ]
    },
    {
        "id": "5aa6837c84af53c0",
        "type": "link out",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "",
        "mode": "link",
        "links": [
            "09c13d6660080a9e"
        ],
        "x": 1425,
        "y": 920,
        "wires": []
    },
    {
        "id": "2fddda6527966677",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 2",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":2}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 960,
        "wires": [
            [
                "5aa6837c84af53c0",
                "76b63ddea61ce5b1"
            ]
        ]
    },
    {
        "id": "ba62f19b42a5081c",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 3",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":3}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1000,
        "wires": [
            [
                "5aa6837c84af53c0",
                "cb9db60b16f57df8"
            ]
        ]
    },
    {
        "id": "ed38aba3837eb7af",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 4",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\": {\"region_id\": 4}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1040,
        "wires": [
            [
                "5aa6837c84af53c0",
                "8668ef70969923c4"
            ]
        ]
    },
    {
        "id": "ec9c608fb99ee855",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 5",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\": {\"region_id\": 5}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1080,
        "wires": [
            [
                "5aa6837c84af53c0",
                "776cb0f58d4a0167"
            ]
        ]
    },
    {
        "id": "a7d208e06324c3f8",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 6",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":6}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1120,
        "wires": [
            [
                "5aa6837c84af53c0",
                "9dcb35836c217104"
            ]
        ]
    },
    {
        "id": "4b8e0477421a11e0",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 7",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\": {\"region_id\": 7}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1160,
        "wires": [
            [
                "5aa6837c84af53c0",
                "dcd25ce11a4c1be2"
            ]
        ]
    },
    {
        "id": "47a64bdd7d804fb3",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 8",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":8}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1200,
        "wires": [
            [
                "5aa6837c84af53c0",
                "f42bbaba3918a204"
            ]
        ]
    },
    {
        "id": "92d0ca57f11f6740",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 9",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":9}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1240,
        "wires": [
            [
                "5aa6837c84af53c0",
                "00b0c574ab7519c0"
            ]
        ]
    },
    {
        "id": "9b2e67a8ab9f6a7b",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 10",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_delete\":{\"region_id\":10}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 1280,
        "wires": [
            [
                "5aa6837c84af53c0",
                "b35d1b8240e37478"
            ]
        ]
    },
    {
        "id": "646055b5fb834ab4",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "topic",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "zigbee2mqtt/Living.Motion/set",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1540,
        "y": 920,
        "wires": [
            [
                "c40fd0fd8f11ade6"
            ]
        ]
    },
    {
        "id": "c40fd0fd8f11ade6",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 1",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":1,\"zones\":[{\"x\":2,\"y\":1},{\"x\":3,\"y\":1}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 920,
        "wires": [
            [
                "cebb925c35150179",
                "591e048d831b202f"
            ]
        ]
    },
    {
        "id": "cebb925c35150179",
        "type": "link out",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "",
        "mode": "link",
        "links": [
            "09c13d6660080a9e"
        ],
        "x": 1835,
        "y": 920,
        "wires": []
    },
    {
        "id": "1d9ed62194557284",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 2",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":2,\"zones\":[{\"x\":2,\"y\":2},{\"x\":3,\"y\":2}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 960,
        "wires": [
            [
                "cebb925c35150179",
                "56f80df860cf83ff"
            ]
        ]
    },
    {
        "id": "adb49031091b093c",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 3",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":3,\"zones\":[{\"x\":2,\"y\":3},{\"x\":3,\"y\":3}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1000,
        "wires": [
            [
                "cebb925c35150179",
                "1d0c9872d7b5272f"
            ]
        ]
    },
    {
        "id": "bbafb2d7588f44d1",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 4",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":4,\"zones\":[{\"x\":2,\"y\":4},{\"x\":3,\"y\":4}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1040,
        "wires": [
            [
                "cebb925c35150179",
                "f48124d8afbf74c0"
            ]
        ]
    },
    {
        "id": "b5de0006461c431f",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 5",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":5,\"zones\":[{\"x\":2,\"y\":5},{\"x\":3,\"y\":5}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1080,
        "wires": [
            [
                "cebb925c35150179",
                "48e1ba0527324388"
            ]
        ]
    },
    {
        "id": "2e85f9e108c90cd7",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 6",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":6,\"zones\":[{\"x\":2,\"y\":6},{\"x\":3,\"y\":7}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1120,
        "wires": [
            [
                "cebb925c35150179",
                "79562e1fbc7b00d2"
            ]
        ]
    },
    {
        "id": "c8e054f576e56f58",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 7",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":7,\"zones\":[{\"x\":1,\"y\":1},{\"x\":3,\"y\":1}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1160,
        "wires": [
            [
                "cebb925c35150179",
                "b80a4c2b66078508"
            ]
        ]
    },
    {
        "id": "f410949de42697c2",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 8",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":8,\"zones\":[{\"x\":4,\"y\":1},{\"x\":4,\"y\":3}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1200,
        "wires": [
            [
                "cebb925c35150179",
                "f254c4b7b9b06a3c"
            ]
        ]
    },
    {
        "id": "a8b618ed1f826f0c",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "reg 9",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":9,\"zones\":[{\"x\":1,\"y\":4},{\"x\":1,\"y\":7}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1240,
        "wires": [
            [
                "cebb925c35150179",
                "20ee7e58f47f6130"
            ]
        ]
    },
    {
        "id": "8b2f2349794948e7",
        "type": "change",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "del 10",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"region_upsert\":{\"region_id\":10,\"zones\":[{\"x\":4,\"y\":4},{\"x\":4,\"y\":7}]}}",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1660,
        "y": 1280,
        "wires": [
            [
                "cebb925c35150179"
            ]
        ]
    },
    {
        "id": "42aa0c5214e677c2",
        "type": "ui_button",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "init",
        "group": "6e3c66513e626ad4",
        "order": 2,
        "width": 2,
        "height": 1,
        "passthru": false,
        "label": "Init",
        "tooltip": "",
        "color": "BLACK",
        "bgcolor": "{{payload}}",
        "className": "",
        "icon": "",
        "payload": "?",
        "payloadType": "str",
        "topic": "CMD",
        "topicType": "msg",
        "x": 950,
        "y": 960,
        "wires": [
            [
                "3872aa19e748932a"
            ]
        ]
    },
    {
        "id": "1f66b62b1797928e",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 960,
        "wires": [
            [
                "2fddda6527966677"
            ]
        ]
    },
    {
        "id": "76b63ddea61ce5b1",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1000,
        "wires": [
            [
                "ba62f19b42a5081c"
            ]
        ]
    },
    {
        "id": "cb9db60b16f57df8",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1040,
        "wires": [
            [
                "ed38aba3837eb7af"
            ]
        ]
    },
    {
        "id": "8668ef70969923c4",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1080,
        "wires": [
            [
                "ec9c608fb99ee855"
            ]
        ]
    },
    {
        "id": "776cb0f58d4a0167",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1120,
        "wires": [
            [
                "a7d208e06324c3f8"
            ]
        ]
    },
    {
        "id": "9dcb35836c217104",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1160,
        "wires": [
            [
                "4b8e0477421a11e0"
            ]
        ]
    },
    {
        "id": "dcd25ce11a4c1be2",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1200,
        "wires": [
            [
                "47a64bdd7d804fb3"
            ]
        ]
    },
    {
        "id": "f42bbaba3918a204",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1240,
        "wires": [
            [
                "92d0ca57f11f6740"
            ]
        ]
    },
    {
        "id": "00b0c574ab7519c0",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1130,
        "y": 1280,
        "wires": [
            [
                "9b2e67a8ab9f6a7b"
            ]
        ]
    },
    {
        "id": "591e048d831b202f",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 960,
        "wires": [
            [
                "1d9ed62194557284"
            ]
        ]
    },
    {
        "id": "56f80df860cf83ff",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1000,
        "wires": [
            [
                "adb49031091b093c"
            ]
        ]
    },
    {
        "id": "1d0c9872d7b5272f",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1040,
        "wires": [
            [
                "bbafb2d7588f44d1"
            ]
        ]
    },
    {
        "id": "f48124d8afbf74c0",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1080,
        "wires": [
            [
                "b5de0006461c431f"
            ]
        ]
    },
    {
        "id": "48e1ba0527324388",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1120,
        "wires": [
            [
                "2e85f9e108c90cd7"
            ]
        ]
    },
    {
        "id": "79562e1fbc7b00d2",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1160,
        "wires": [
            [
                "c8e054f576e56f58"
            ]
        ]
    },
    {
        "id": "b80a4c2b66078508",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1200,
        "wires": [
            [
                "f410949de42697c2"
            ]
        ]
    },
    {
        "id": "f254c4b7b9b06a3c",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1240,
        "wires": [
            [
                "a8b618ed1f826f0c"
            ]
        ]
    },
    {
        "id": "20ee7e58f47f6130",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1530,
        "y": 1280,
        "wires": [
            [
                "8b2f2349794948e7"
            ]
        ]
    },
    {
        "id": "b35d1b8240e37478",
        "type": "delay",
        "z": "a991523747fb3b93",
        "g": "0e2a9fc870fe4f89",
        "name": "1sec",
        "pauseType": "delay",
        "timeout": "5",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 1390,
        "y": 1300,
        "wires": [
            [
                "646055b5fb834ab4"
            ]
        ]
    },
    {
        "id": "6e3c66513e626ad4",
        "type": "ui_group",
        "name": "Area",
        "tab": "255d43f52db03520",
        "order": 2,
        "disp": false,
        "width": "4",
        "collapse": false,
        "className": ""
    },
    {
        "id": "255d43f52db03520",
        "type": "ui_tab",
        "name": "Living",
        "icon": "mi-chair",
        "order": 7,
        "disabled": false,
        "hidden": false
    }
]`
2) Earlier I was receiving the ACTION update ... but not anymore (I was using DEV versions all the time)

**Comment by juergen-huang** [comment]
What is the current status of this issue?
I still can't set the area for FP1 just now, even manually through the developer tools.

**Comment by xX-Nexus-Xx** [comment]
I'm using 1.38.0-dev and above flow for Node-red is able to configure the area's properly .. somehow I have rarely success via the dev tools

**Comment by andreasbuff** [comment]
Problem still exists: "Apply" Button has no effect and "Region upsert" Definitions are not stored??   (updated FP1 to most recent Firmware via Aquar-Hub and reconnected after this to Zigbee2Mqtt

Version: [1.40.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.1) commit: [403d3c0](https://github.com/Koenkk/zigbee2mqtt/commit/403d3c0)

**Comment by Der-Botschafter** [comment]
Same problem here. Brand new aqara fp1 sensor.

Z2M Version: 1.41.0
Coordinator revision: 20230507
