### ISSUE TITLE
Device name change button disappeared from GUI

### ISSUE THREAD

**Issue by PeterKawa** [nurikk/z2m-frontend#2003]
### What happened?

```
Zigbee2MQTT version: 1.36.1-dev commit: df23240
Coordinator type: EmberZNet
Coordinator revision: 7.4.1 [GA]
Version frontend: 0.6.163
zigbee_herdsman_converters_version: 19.27.0
zigbee_herdsman_version: 0.43.0
```

Hello,

With this dev commit (at least I noticed it just now) I can't find how to rename my (new) devices anymore, using the frontend GUI on an Android 10 phone;
It was positioned at the left of the 'interview' and 'delete' buttons at the bottom, see screenshot:

![Screenshot_20240425-191735_Home Assistant.jpg](https://github.com/nurikk/zigbee2mqtt-frontend/assets/74005072/cad763e2-5e5c-47e1-89ba-d21699c9bd30)

No biggie, I know how to add / edit the 'friendly_name' to the config yaml.
But it was quite convenient to use the GUI.

Thanks for all the work and efforts
~Peet

### What browsers are you seeing the problem on?

Firefox, Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by cloudbr34k84** [comment]
Yeah on your phone if you change it to landscape it shows, so i think its an oversight

**Comment by PeterKawa** [comment]
Thanks. Landscape doesn't change anything here, but changing the browsers to 'Desktop mode' reveals the button.

**Comment by cloudbr34k84** [comment]
u sure? when i view it on my mobile in landscape i see the name change button?
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/58960644/e7d3f456-2c68-4f7a-9741-401184ef09c0)

**Comment by smilisav** [comment]
The rename button appears for me, but the checkbox to also update the associated HA entities has disappeared since updating to 1.37.0. :( 

This is on desktop view.
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/13689196/369803be-6e9a-4777-8284-8fce14e45499)

On mobile view, the rename buttons don't even show.

**Comment by S33G** [comment]
Fixed:
https://github.com/nurikk/zigbee2mqtt-frontend/pull/2012

**Comment by cloudbr34k84** [comment]
> Fixed: #2012

I just upgraded to 1.37.0-dev commit: [3a61f0a] and its still not fixed on mobile. I have cleared cache and done a force stop on mobile.

**Comment by S33G** [comment]
> > Fixed: #2012
> 
> I just upgraded to 1.37.0-dev commit: [3a61f0a] and its still not fixed on mobile. I have cleared cache and done a force stop on mobile.

Thanks for testing, although it's not currently merged into dev.

**Comment by S33G** [comment]
> > Fixed: #2012
> 
> I just upgraded to 1.37.0-dev commit: [3a61f0a] and its still not fixed on mobile. I have cleared cache and done a force stop on mobile.

https://github.com/nurikk/zigbee2mqtt-frontend/releases/tag/0.6.167

**Comment by PeterKawa** [comment]
Thanx! It's fixed.

**Comment by PeterKawa** [comment]
Fixed
