### ISSUE TITLE
table framework

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#47]
Maybe you can use this framework for the devices table

https://github.com/wenzhixin/bootstrap-table

I use it in many projects myself, and pretty easy to use

**Comment by nurikk** [comment]
Which problem should solve this table framework?

**Comment by timoline** [comment]
one small example
You don't have to bother about search and filter possibilties, it's all in the framework

But in general, a framework doesn't solve anything, but it will make your life easier :-)

**Comment by timoline** [comment]
maybe this one?
https://github.com/ashvin27/react-datatable
